const TaylorSwift = {
  TaylorSwift: [
    "Tim McGraw",
    "Picture to Burn",
    "Teardrops on My Guitar",
    "A Place in this World",
    "Cold as You",
    "The Outside",
    "Tied Together with a Smile",
    "Stay Beautiful",
    "Should've Said No",
    "Mary's Song",
    "Our Song",
  ],
  Fearless: [
    "Fearless",
    "Fifteen",
    "Love Story",
    "Hey Stephen",
    "White Horse",
    "You Belong with Me",
    "Breathe",
    "Tell Me Why",
    "You're Not Sorry",
    "The Way I Loved You",
    "Forever&Always",
    "The Best Day",
    "Change",
  ],
  SpeakNow: [
    "Mine",
    "Sparks Fly",
    "Back To December",
    "Speak Now",
    "Dear John",
    "Mean",
    "The Story of Us",
    "Never Grow Up",
    "Enchanted",
    "Better than Revenge",
    "Innocent",
    "Haunted",
    "Last Kiss",
    "Long Live",
  ],
  Red: [
    "State of Grace",
    "Red",
    "Treacherous",
    "I Knew You Were Trouble",
    "All Too Well",
    "22",
    "I Almost Do",
    "We Are Never Ever Getting Back Together",
    "Stay Stay Stay",
    "The Last Time",
    "Holy Ground",
    "Sad Beautiful Tragic",
    "The Lucky One",
    "Everything Has Changed",
    "Starlight",
    "Begin Again",
  ],
  1989: [
    "Welcome to New York",
    "Blank Space",
    "Style",
    "Out of the Woods",
    "All You Had to Do Was Stay",
    "Shake it Off",
    "I Wish You Would",
    "Bad Blood",
    "Wildest Dreams",
    "How You Get the Girl",
    "This Love",
    "I Know Places",
    "Clean",
  ],
  Reputation: [
    "...Ready for It?",
    "End Game",
    "I Did Something Bad",
    "Don't Blame Me",
    "Delicate",
    "Look What You Made Me Do",
    "So It Goes...",
    "Gorgeous",
    "Getaway Car",
    "King of My Heart",
    "Dancing with Our Hands Tied",
    "Dress",
    "This Is Why We Can't Have Nice Things",
    "Call It What You Want",
    "New Year's Day",
  ],
  Lover: [
    "I Forgot That You Existed",
    "Cruel Summer",
    "Lover",
    "The Man",
    "The Archer",
    "I Think He Knows",
    "Miss Americana & the Heartbreak Princes",
    "Paper Rings",
    "Cornelia Street",
    "Death by a Thousand Cuts",
    "London Boy",
    "Soon You'll Get Better",
    "False God",
    "You Need to Calm Down",
    "Afterglow",
    "Me!",
    "It's Nice to Have a Friend",
    "Daylight",
  ],
  Folklore: [
    "The 1",
    "Cardigan",
    "The Last Great Americana Dynasty",
    "Exile",
    "My Tears Ricochet",
    "Mirrorball",
    "Seven",
    "August",
    "This Is Me Trying",
    "Illicit Affairs",
    "Invisible String",
    "Mad Woman",
    "Epiphany",
    "Betty",
    "Peace",
    "Hoax",
  ],
  Evermore: [
    "Willow",
    "Champagne Problems",
    "Gold Rush",
    "Tis the Damn Season",
    "Tolerate It",
    "No Body, No Crime",
    "Happiness",
    "Dorothea",
    "Coney Island",
    "Ivy",
    "Cowboy like Me",
    "Long Story Short",
    "Marjorie",
    "Closure",
    "Evermore",
  ],
  Midgnights: [
    "Lavander Haze",
    "Marron",
    "Anti-Hero",
    "Snow on the Beach",
    "You're on Your Own,Kid",
    "Midnight Rain",
    "Question...?",
    "Vigilante Shit",
    "Bejeweled",
    "Labyrinth",
    "Karma",
    "Sweet Nothing",
    "Mastermind",
  ],
};
